### PR TITLE
Fixed _sortByTitle

### PR DESCRIPTION
**Pull request by buestad**
The sortByTitle option did not work for me. I have added the option and fixed the code to sort the namespaces and pages correctly.
I also added a leading zero fix

### CODE REVIEW

**Comment by buestad** [comment]
build failed... I'll have to try to figure out why and how this works...

**Comment by buestad** [comment]
Can you check this @splitbrain ?
Travis CI checks are new to me. What have I done wrong?

**Comment by splitbrain** [comment]
I think those errors are unrelated to your changes

**Comment by fabienli** [comment]
I've tried the code from this PR into my dokuwiki instance, and it seems to work great.
Could we try again if it could be integrated?

**Comment by splitbrain** [comment]
obsolete with the recent refactoring

**Pull request closed without merging**
